config/routes.rb
PortfolioBlog::Application.routes.draw do
  resources :media

  resources :html_snippets

  resources :roles

  get "sessions/new"

  get "pages/home"

  resources :users

  resources :comments

  resources :categories

  resources :attachments

  resources :posts do
    collection do
      post 'edit_multiple'
      put 'update_multiple'
      get 'manage_selected_categories'
      post 'categorize_selected'
    end
  end

  namespace :api, constraints: {format: :json}, defaults: {format: :json} do
    namespace :v1 do
      namespace :admin do
        resources :blogs
      end
    end
  end

  resource :sessions

  root :to => 'pages#home'

end

app/models/attachment.rb
class Attachment < ActiveRecord::Base

  belongs_to :user, :foreign_key => 'attacher_id'
  belongs_to :attachable, polymorphic: true

  validates_presence_of :user

  def self.get_attachable_types
    ['HtmlSnippet', 'Medium']
  end
end

app/models/categorized_post.rb
class CategorizedPost < ActiveRecord::Base
  # attr_accessible :category_id, :post_id

  belongs_to :category
  belongs_to :post

  validates_presence_of :category_id, :post_id
end

app/models/category.rb
class Category < ActiveRecord::Base
  # attr_accessible :name, :parent_id

  validates_presence_of :name
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  # attr_accessible :content, :guest_name

  has_one :categorized_post
  has_one :post, :through => :categorized_post

  validates_presence_of :guest_name, :content
end

app/models/commentary.rb
class Commentary < ActiveRecord::Base
  # attr_accessible :comment_id, :post_id

  belongs_to :post
  belongs_to :comment

  validates_presence_of :post_id, :comment_id
end

app/models/html_snippet.rb
class HtmlSnippet < ActiveRecord::Base
  # attr_accessible :css, :description, :html, :javascript, :name

  has_many :attachments, as: :attachable

  mount_uploader :image, ImageUploader

  def render(data)
    require "CanvasToImage"
    File.open("tmp/reply.png", "wb") { |f| f.write(CanvasToImage::decode_data_uri(data)[0]) }

# binding.pry
    file = File.open("tmp/reply.png", "r")
  end
end

app/models/medium.rb
## Medium as in the type of media used to create a work of art.
class Medium < ActiveRecord::Base
  # attr_accessible :description, :file, :media_type, :name

  has_many :attachments, as: :attachable

  mount_uploader :file, FileUploader

end

app/models/post.rb
class Post < ActiveRecord::Base
	# attr_accessible :image, :title, :description, :content, :user_id, :html, :css, :javascript, :status_type_id

	mount_uploader :image, ImageUploader

	has_many :categorized_posts
	has_many :categories, :through => :categorized_posts
	has_many :commentaries
	has_many :comments, :through => :commentaries

	has_many :attachments

	belongs_to :user

	has_one :status_type

	# validations
  validates_presence_of :title, :description, :content

	class << self
		def by_category(category_name)
			joins(:categories).where(["name = ?", category_name])
		end
	end
end

app/models/role.rb
class Role < ActiveRecord::Base
  # attr_accessible :name

  validates_presence_of :name
end

app/models/status_type.rb
class StatusType < ActiveRecord::Base
  # attr_accessible :name, :public_use

end

app/models/user.rb
class User < ActiveRecord::Base
  # attr_accessible :name, :password_digest, :email, :role_id, :password, :password_confirmation
  has_secure_password

  validates_format_of :email, :with => /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\Z/i, :on => :create
  validates_uniqueness_of :email
  validates_presence_of :email

  has_many :posts

  belongs_to :role
end

app/helpers/application_helper.rb
module ApplicationHelper

  def icon_submit_link(icon_name, link_text, link_class = "")
    icon_html =  content_tag('i','', :class=>"#{icon_name}") + "#{link_text}"
    link_to(icon_html, "#", :onclick=>"getForm(this).submit(); return false", :class=> link_class)
  end
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/media_helper.rb
module MediaHelper
end

app/helpers/pages_helper.rb
module PagesHelper
  def programing_languages
    %w{ HTML CSS JS XML Ruby Python PHP MySQL AS2 AS3}.map do |p|
      OpenStruct.new({name: p})
    end
  end

  def development_frameworks
   ["Ruby on Rails","Angularjs","Sinatra","Nodejs","Flex"].map do |p|
      OpenStruct.new({name: p,slug: p.parameterize})
    end
  end

  def design_software
    %w{Flash Illustrator Photoshop AfterEffects Fireworks DreamWeaver}.map do |s|
      OpenStruct.new({name:s})
    end
  end
end

app/helpers/posts_helper.rb
module PostsHelper
	def recent_blogs
		Post.by_category("blog")
	end

	def recent_experiments
		Post.by_category("experiment")
	end
end

app/helpers/roles_helper.rb
module RolesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <title><%= content_for?(:title) ? yield(:title) : "Brian Mehrman" %></title>

    <% if content_for?(:css) %>
      <%= yield :css %>
    <% else %>
      <%= stylesheet_link_tag  "application" %>
    <% end -%>

    <%= csrf_meta_tags %>
    <% if content_for?(:head) %>
      <%= yield :head %>
    <% end %>
  </head>

  <body>
    <div class="off-canvas-wrap" data-offcanvas>
      <div class="inner-wrap">
      <% if content_for?(:navigation) %>
        <%= yield :navigation %>
      <% else %>
        <%= render "shared/navigation" %>
      <% end -%>
      <section class="main-section">
        <% if content_for?(:header) %>
          <%= yield :header %>
        <% else %>
          <%= render "shared/header" %>
        <% end -%>

        <%= yield %>

        <% if content_for?(:footer) %>
          <%= yield :footer %>
        <% else %>
          <%= render "shared/footer" %>
        <% end -%>
      </section>
        <a class="exit-off-canvas"></a>
      </div>
    </div>

    <%= javascript_include_tag "vendor/modernizr" %>
     <% if content_for?(:javascript) %>
      <%= yield :javascript %>
    <% else %>
      <%= javascript_include_tag "application" %>
    <% end -%>
  </body>
</html>

app/views/layouts/facebox.html.erb
<div id="facebox-wrapper">
	<%= yield %>	 
</div>

app/views/shared/_footer.html.erb
<footer class="row">
  <div class="large-12 columns">
    <hr/>
    <div class="row">
      <div class="large-6 columns">
        <p>2015© Copyright BrianMehrman.com</p>
      </div>
      <div class="large-6 columns">
        <ul class="inline-list right">
          <li><a href="https://twitter.com/brianmehrman"><i class="fa fa-twitter"> </i></a></li>
          <li><a href="https://github.com/BrianMehrman"><i class="fa fa-github"> </i></a></li>
          <li><a href="https://www.linkedin.com/pub/brian-mehrman/1a/a1a/208"><i class="fa fa-linkedin"> </i></a></li>
        </ul>
      </div>
    </div>
  </div>
</footer>

app/views/shared/_header.html.erb
<div class="row news-border title">
  <a href="/">
    <div class="small-5 columns text-right"><h1>Brian</h1></div>
    <div class="small-2 columns text-center logo"><%= image_tag "logo.svg" %></div>
    <div class="small-5 columns text-left"><h1>Mehrman</h1></div>
  </a>
</div>
<div class="row news-border">
  <hr class='news' />
  <div class="small-12 columns text-center">
    <h3><small>It's about the code.</small></h1>
  </div>
  <hr class="news" />
  <% if logged_in? %>
    <p class='greet-user' >
      Hello, <%= current_user.name %>
    </p>
  <% end -%>
</div>

app/views/shared/_navigation.html.erb
  <div class="contain-to-grid sticky">
  <nav class="tab-bar top-bar " data-topbar role="navigation" data-options="sticky_on: large" >
    <div class="top-bar-section tab-bar-section">
      <ul class="left" >
          <li><%= link_to posts_path(:category=>"blog"), class: "", role: "button", tabindex:"0", title: "View Blog", "data-tooltip"=>"", "aria-haspopup"=>"true",'aria-label'=>"Blog" do %>
            <span class=""><i class='fa fa-book'></i>
            Blog</span>
          <% end -%></li>
          <li><%= link_to posts_path(:category=>"experiments"), class: "", role: "button", tabindex:"1", title: "View Experiments", "data-tooltip"=>"", "aria-haspopup"=>"true", 'aria-label'=>"Experiments" do %>
            <span class=""><i class='fa fa-flask'></i>
            Experiments</span>
          <% end -%></li>
      </ul>
    </div>

    <section class="right-small">
      <a class="right-off-canvas-toggle menu-icon" ><span></span></a>
    </section>
  </nav>
  <% if logged_in? %>
    <aside class="right-off-canvas-menu">
      <ul class="off-canvas-list">
        <li><label>Admin</label></li>
        <li >
          <%= link_to "Add Post", new_post_path %>
        </li>
        <li >
          <%= link_to "Manage Posts", posts_path %>
        </li>
        <li >
          <%= link_to "Add Catagory", new_category_path %>
        </li>
        <li >
          <%= link_to "Manage category", categories_path %>
        </li>
        <li >
          <%= link_to "Edit User", user_path(current_user), :class=> 'edit-user' %>
        </li>
        <li >
          <%= link_to "Sign Out", sessions_path, :method => :delete, :class=> 'sign-out' %>
        </li>
      </ul>
    </aside>
  <% else %>
    <aside class="right-off-canvas-menu">
      <ul class="off-canvas-list">
      <li class=" sign_in">
        <%= link_to "Sign In", '#', :class=>'sign-in' %>
        <span class="loading icon-spinner icon-spin" style="display:none;"></span>
        <div class="new-session">
          <%= form_tag sessions_path do %>
            <p><%= label_tag 'Email' %> <%= text_field_tag :email %></p>
            <p><%= label_tag 'Password' %><%= password_field_tag :password %></p>
            <div class="input"><%= submit_tag 'Sign In' %></div>
          <% end %>
        </div>
      </li>
      </ul>
    </aside>
  <% end -%>
</div>

app/views/shared/_sidebar.html.erb
<div class="sidebar">
	<div class="top_posts">
	</div>
	<div class="info">
	</div>
</div>