config/routes.rb
PortfolioBlog::Application.routes.draw do
  resources :media

  resources :html_snippets

  resources :roles

  get "sessions/new"

  get "pages/home"

  resources :users

  resources :comments

  resources :categories

  resources :attachments

  resources :posts do
    collection do
      post 'edit_multiple'
      put 'update_multiple'
      get 'manage_selected_categories'
      post 'categorize_selected'
    end
  end

  namespace :api, constraints: {format: :json}, defaults: {format: :json} do
    namespace :v1 do
      namespace :admin do
        resources :blogs
      end
    end
  end

  resource :sessions

  root :to => 'pages#home'

end

app/models/attachment.rb
class Attachment < ActiveRecord::Base

  belongs_to :user, :foreign_key => 'attacher_id'
  belongs_to :attachable, polymorphic: true

  validates_presence_of :user

  def self.get_attachable_types
    ['HtmlSnippet', 'Medium']
  end
end

app/controllers/attachments_controller.rb
class AttachmentsController < ApplicationController
  # GET /attachments
  # GET /attachments.json
  def index
    @attachments = Attachment.all

    @post = Post.find(params[:post_id]) if params[:post_id]

    respond_to do |format|
      # format.html # index.html.erb
      format.js { render :layout=>false }
      format.json { render json: @attachments }
    end
  end

  # GET /attachments/1
  # GET /attachments/1.json
  def show
    @attachment = Attachment.find(params[:id])
    @post = Post.find(params[:post_id])

    respond_to do |format|
      # format.html # show.html.erb
      format.js {render :layout=>false}
      format.json { render json: @attachment }
    end
  end

  # GET /attachments/new
  # GET /attachments/new.json
  def new
    @attachment = Attachment.new
    @post = (params[:post_id] == 0 ? Post.find(params[:post_id]) : Post.new)

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @attachment }
    end
  end

  # GET /attachments/1/edit
  def edit
    @post = Post.find(params[:post_id])

    @attachment = Attachment.find(params[:id])
    # TODO: add attachments edit form

  end

  # POST /attachments
  # POST /attachments.json
  def create
    @post = Post.find(params[:post_id])

    @attachment = Attachment.new(attachment_params)

    respond_to do |format|
      if @attachment.save
        # TODO: redirect to attachments edit page
        format.html { redirect_to edit_post_path(@post), notice: 'Attachment was successfully created.' }
        format.json { render json: @attachment, status: :created, location: @attachment }
      else
        format.html { render action: "new" }
        format.json { render json: @attachment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /attachments/1
  # PUT /attachments/1.json
  def update
    @attachment = Attachment.find(params[:id])

    respond_to do |format|
      if @attachment.update_attributes(attachment_params)
        format.html { redirect_to @attachment, notice: 'Attachment was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @attachment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /attachments/1
  # DELETE /attachments/1.json
  def destroy
    @attachment = Attachment.find(params[:id])
    @attachment.destroy

    respond_to do |format|
      format.html { redirect_to attachments_url }
      format.json { head :no_content }
    end
  end

  private

    def attachment_params
      params.require(:attachment).permit(:attachable_id, :attachable_type, :attacher_id, :post_id, :slug_name)
    end
end

app/helpers/attachments_helper.rb
module AttachmentsHelper
end

app/views/attachments/_attachment.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Slug Name:</b>
  <%= @attachment.slug_name %>
</p>

<p>
  <b>Attachable type:</b>
  <%= @attachment.attachable_type %>
</p>

<p>
  <b>Attacher:</b>
  <%= @attachment.user ? @attachment.user.name : "No Attacher" %>
</p>

<p>
  <span>Insert Into Content</span>
</p>
<p>
  <span>Copy to Clipboard</span>
</p>

<%= link_to 'Close', "#" %>

app/views/attachments/_attachments.html.erb
<ul>
<% @attachments.each do |attachment| %>
  <li class="attachment" data-attachment-id="<%= attachment.attachable_id %>"  >
    <%= attachment.id %>
    <%= attachment.slug_name %>
  </li>
<% end %>
</ul>
<%= link_to 'New Attachment', '#new_attachment', class: "new_button" %>

<br />

app/views/attachments/_form.html.erb
<%=form_for(@attachment) do |f| %>
  <% if @attachment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@attachment.errors.count, "error") %> prohibited this attachment from being saved:</h2>

      <ul>
      <% @attachment.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <%= f.hidden_field :attachable_id, :value=>current_user.id %>

  <div class="field">
    <%= f.label :slug_name %>
    <%= f.text_field :slug_name %>
  </div>

  <div class="field">
    <%= f.label :attachable_type %>
    <%= f.select :attachable_type, Attachment.get_attachable_types.map{|t| [t,t.humanize]} %>
  </div>

  <div class="field">
    <%# assign attachment to content %>
    <%# assign_attachment %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/attachments/edit.html.erb
<h1>Editing attachment</h1>

<%= render 'form' %>

<%= link_to 'Show', post_attachment_path([@post,@attachment]) %> |
<%= link_to 'Back', :back %>

app/views/attachments/index.js.erb
$("#attachment_index").removeClass('loading').html("<%= j render 'attachments'%>");

$(".attachment").hover(attachment_item_init);

app/views/attachments/new.html.erb
<h1>New attachment</h1>

<%= render 'form' %>

<%= link_to 'Back', attachments_path %>

app/views/attachments/new.js.erb
$("#attachment_container").html("<%# j render 'new' %>")

app/views/attachments/qqindex.html.erb
<h1>Listing attachments</h1>

<ul>

<% @attachments.each do |attachment| %>
  <li data-attachment-id="<%= attachment.attachable_id %>"
      data-show-link="<%= link_to 'Show', post_attachment_path(@post.id, attachment.id) %>"
      data-edit-link="<%= link_to 'Edit', edit_post_attachment_path(@post.id,attachment.id) %>"  >
    <<%= attachment.slug_name %>
  </li>
<% end %>
</ul>

<br />

<%= link_to 'New Attachment', new_post_attachment_path(@post.id) %>

app/views/attachments/show.js.erb
$("#attachment_show_edit").fadeOut(400, function(){
  $(this).html("<%= j render 'attachment' %>").fadeIn(500);
});