config/routes.rb
PortfolioBlog::Application.routes.draw do
  resources :media

  resources :html_snippets

  resources :roles

  get "sessions/new"

  get "pages/home"

  resources :users

  resources :comments

  resources :categories

  resources :attachments

  resources :posts do
    collection do
      post 'edit_multiple'
      put 'update_multiple'
      get 'manage_selected_categories'
      post 'categorize_selected'
    end
  end

  namespace :api, constraints: {format: :json}, defaults: {format: :json} do
    namespace :v1 do
      namespace :admin do
        resources :blogs
      end
    end
  end

  resource :sessions

  root :to => 'pages#home'

end

app/models/attachment.rb
class Attachment < ActiveRecord::Base

  belongs_to :user, :foreign_key => 'attacher_id'
  belongs_to :attachable, polymorphic: true

  validates_presence_of :user

  def self.get_attachable_types
    ['HtmlSnippet', 'Medium']
  end
end

app/models/categorized_post.rb
class CategorizedPost < ActiveRecord::Base
  # attr_accessible :category_id, :post_id

  belongs_to :category
  belongs_to :post

  validates_presence_of :category_id, :post_id
end

app/models/category.rb
class Category < ActiveRecord::Base
  # attr_accessible :name, :parent_id

  validates_presence_of :name
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  # attr_accessible :content, :guest_name

  has_one :categorized_post
  has_one :post, :through => :categorized_post

  validates_presence_of :guest_name, :content
end

app/models/commentary.rb
class Commentary < ActiveRecord::Base
  # attr_accessible :comment_id, :post_id

  belongs_to :post
  belongs_to :comment

  validates_presence_of :post_id, :comment_id
end

app/models/html_snippet.rb
class HtmlSnippet < ActiveRecord::Base
  # attr_accessible :css, :description, :html, :javascript, :name

  has_many :attachments, as: :attachable

  mount_uploader :image, ImageUploader

  def render(data)
    require "CanvasToImage"
    File.open("tmp/reply.png", "wb") { |f| f.write(CanvasToImage::decode_data_uri(data)[0]) }

# binding.pry
    file = File.open("tmp/reply.png", "r")
  end
end

app/models/medium.rb
## Medium as in the type of media used to create a work of art.
class Medium < ActiveRecord::Base
  # attr_accessible :description, :file, :media_type, :name

  has_many :attachments, as: :attachable

  mount_uploader :file, FileUploader

end

app/models/post.rb
class Post < ActiveRecord::Base
	# attr_accessible :image, :title, :description, :content, :user_id, :html, :css, :javascript, :status_type_id

	mount_uploader :image, ImageUploader

	has_many :categorized_posts
	has_many :categories, :through => :categorized_posts
	has_many :commentaries
	has_many :comments, :through => :commentaries

	has_many :attachments

	belongs_to :user

	has_one :status_type

	# validations
  validates_presence_of :title, :description, :content

	class << self
		def by_category(category_name)
			joins(:categories).where(["name = ?", category_name])
		end
	end
end

app/models/role.rb
class Role < ActiveRecord::Base
  # attr_accessible :name

  validates_presence_of :name
end

app/models/status_type.rb
class StatusType < ActiveRecord::Base
  # attr_accessible :name, :public_use

end

app/models/user.rb
class User < ActiveRecord::Base
  # attr_accessible :name, :password_digest, :email, :role_id, :password, :password_confirmation
  has_secure_password

  validates_format_of :email, :with => /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\Z/i, :on => :create
  validates_uniqueness_of :email
  validates_presence_of :email

  has_many :posts

  belongs_to :role
end

app/controllers/html_snippets_controller.rb
class HtmlSnippetsController < ApplicationController
  # GET /html_snippets
  # GET /html_snippets.json
  def index
    @html_snippets = HtmlSnippet.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @html_snippets }
    end
  end

  # GET /html_snippets/1
  # GET /html_snippets/1.json
  def show
    @html_snippet = HtmlSnippet.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @html_snippet }
    end
  end

  # GET /html_snippets/new
  # GET /html_snippets/new.json
  def new
    @html_snippet = HtmlSnippet.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @html_snippet }
    end
  end

  # GET /html_snippets/1/edit
  def edit
    @html_snippet = HtmlSnippet.find(params[:id])
  end

  # POST /html_snippets
  # POST /html_snippets.json
  def create


    @html_snippet = HtmlSnippet.new(html_snippet_params)

    respond_to do |format|
      if @html_snippet.save
        format.html { redirect_to @html_snippet, notice: 'Html snippet was successfully created.' }
        format.json { render json: @html_snippet, status: :created, location: @html_snippet }
      else
        format.html { render action: "new" }
        format.json { render json: @html_snippet.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /html_snippets/1
  # PUT /html_snippets/1.json
  def update
    @html_snippet = HtmlSnippet.find(params[:id])

    respond_to do |format|
      if @html_snippet.update_attributes(html_snippet_params)
        format.html { redirect_to @html_snippet, notice: 'Html snippet was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @html_snippet.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /html_snippets/1
  # DELETE /html_snippets/1.json
  def destroy
    @html_snippet = HtmlSnippet.find(params[:id])
    @html_snippet.destroy

    respond_to do |format|
      format.html { redirect_to html_snippets_url }
      format.json { head :no_content }
    end
  end

  private

  def html_snippet_params
    params.require(:html_snippet).permit(:name, :description, :html, :css, :javascript, :image)

  end
end

app/helpers/application_helper.rb
module ApplicationHelper

  def icon_submit_link(icon_name, link_text, link_class = "")
    icon_html =  content_tag('i','', :class=>"#{icon_name}") + "#{link_text}"
    link_to(icon_html, "#", :onclick=>"getForm(this).submit(); return false", :class=> link_class)
  end
end

app/helpers/attachments_helper.rb
module AttachmentsHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/html_snippets_helper.rb
module HtmlSnippetsHelper
end

app/helpers/media_helper.rb
module MediaHelper
end

app/helpers/pages_helper.rb
module PagesHelper
  def programing_languages
    %w{ HTML CSS JS XML Ruby Python PHP MySQL AS2 AS3}.map do |p|
      OpenStruct.new({name: p})
    end
  end

  def development_frameworks
   ["Ruby on Rails","Angularjs","Sinatra","Nodejs","Flex"].map do |p|
      OpenStruct.new({name: p,slug: p.parameterize})
    end
  end

  def design_software
    %w{Flash Illustrator Photoshop AfterEffects Fireworks DreamWeaver}.map do |s|
      OpenStruct.new({name:s})
    end
  end
end

app/helpers/posts_helper.rb
module PostsHelper
	def recent_blogs
		Post.by_category("blog")
	end

	def recent_experiments
		Post.by_category("experiment")
	end
end

app/helpers/roles_helper.rb
module RolesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/html_snippets/_form.html.erb
<%= form_for(@html_snippet) do |f| %>
  <% if @html_snippet.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@html_snippet.errors.count, "error") %> prohibited this html_snippet from being saved:</h2>

      <ul>
      <% @html_snippet.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div id="tabs" class="tabs html_editor">
    <% content_for :head do %>
      <script>
      $(function(){

        var code_mirror = new LocalMirror('#htmlArea','#cssArea','#jsArea');
        $(".tabs").tabs();

      });
      </script>
    <% end %>
    
    <ul>
      <li><%= link_to "Content", "#tabs-1" %></li>
      <li><%= link_to "HTML",    "#tabs-2" %></li>
      <li><%= link_to "CSS",     "#tabs-3" %></li>
      <li><%= link_to "JS",      "#tabs-4" %></li>
      <li><%= link_to "Preview", "#tabs-5" %></li>
    </ul>
    <div id="tabs-1">
      <div class="field post_title">
        <%= f.label :name %> <%= f.text_field :name %>
      </div>
      <div class="field post_description">
        <%= f.label :description %> <%= f.text_field :description %>
      </div>
      <div class="clear"></div>
    </div>

    <div id="tabs-2" class="tab">
      <h3>HTML</h3>
      <%= f.text_area :html, :id=>'htmlArea' %>
    </div>
    
    <div id="tabs-3" class="tab">
      <h3>CSS</h3>
      <%= f.text_area :css, :id=>'cssArea' %>
      <div class="edit_control_panel"><input type="button" id="update" value="Update" /></div>
    </div>
    
    <div id="tabs-4" class="tab" >
      <h3>Javascript</h3>
      <%= f.text_area :javascript, :id=>'jsArea' %>
      <div class="edit_control_panel"><input type="button" id="update" value="Update" /></div>
    </div>
    
    <div id="tabs-5" class="tab">
      <h3>HTML Preview</h3>
      <iframe id="preview"></iframe>
      <div class="edit_control_panel"><input type="button" id="update" value="Update" /></div>
    </div>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/html_snippets/edit.html.erb
<h1>Editing html_snippet</h1>

<%= render 'form' %>

<%= link_to 'Show', @html_snippet %> |
<%= link_to 'Back', html_snippets_path %>

app/views/html_snippets/index.html.erb
<h1>Listing html_snippets</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Description</th>
    <th>Html</th>
    <th>Css</th>
    <th>Javascript</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @html_snippets.each do |html_snippet| %>
  <tr>
    <td><%= html_snippet.name %></td>
    <td><%= html_snippet.description %></td>
    <td><%= html_snippet.html %></td>
    <td><%= html_snippet.css %></td>
    <td><%= html_snippet.javascript %></td>
    <td><%= link_to 'Show', html_snippet %></td>
    <td><%= link_to 'Edit', edit_html_snippet_path(html_snippet) %></td>
    <td><%= link_to 'Destroy', html_snippet, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Html snippet', new_html_snippet_path %>

app/views/html_snippets/new.html.erb
<h1>New html_snippet</h1>

<%= render 'form' %>

<%= link_to 'Back', html_snippets_path %>

app/views/html_snippets/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @html_snippet.name %>
</p>

<p>
  <b>Description:</b>
  <%= @html_snippet.description %>
</p>

<p>
  <b>Html:</b>
  <%= @html_snippet.html %>
</p>

<p>
  <b>Css:</b>
  <%= @html_snippet.css %>
</p>

<p>
  <b>Javascript:</b>
  <%= @html_snippet.javascript %>
</p>


<%= link_to 'Edit', edit_html_snippet_path(@html_snippet) %> |
<%= link_to 'Back', html_snippets_path %>