config/routes.rb
PortfolioBlog::Application.routes.draw do
  resources :media

  resources :html_snippets

  resources :roles

  get "sessions/new"

  get "pages/home"

  resources :users

  resources :comments

  resources :categories

  resources :attachments

  resources :posts do
    collection do
      post 'edit_multiple'
      put 'update_multiple'
      get 'manage_selected_categories'
      post 'categorize_selected'
    end
  end

  namespace :api, constraints: {format: :json}, defaults: {format: :json} do
    namespace :v1 do
      namespace :admin do
        resources :blogs
      end
    end
  end

  resource :sessions

  root :to => 'pages#home'

end

app/models/post.rb
class Post < ActiveRecord::Base
	# attr_accessible :image, :title, :description, :content, :user_id, :html, :css, :javascript, :status_type_id

	mount_uploader :image, ImageUploader

	has_many :categorized_posts
	has_many :categories, :through => :categorized_posts
	has_many :commentaries
	has_many :comments, :through => :commentaries

	has_many :attachments

	belongs_to :user

	has_one :status_type

	# validations
  validates_presence_of :title, :description, :content

	class << self
		def by_category(category_name)
			joins(:categories).where(["name = ?", category_name])
		end
	end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

  layout 'facebox', :only => [:manage_selected_categories, :categorize_selected]
  def index
    @category = params[:category]
    @posts = @category.present? ? Post.by_category(@category) : Post.all
  end

  def show
    @post = Post.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @post }
    end
  end

  def new
    # create a post with the status of draft
    @post = Post.new(user_id: session[:user_id],status_type_id:1,title:nil,description:nil)

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @post }
    end
  end

  # GET /posts/1/edit
  def edit
    @post = Post.find(params[:id])
  end

  # POST /posts
  # POST /posts.json
  def create
    # create post preview
    # params[:post][:image] = file

    @post = Post.find(params[:post][:id])
    post_params[:image] = parse_image(post_params[:image])

    respond_to do |format|
      if @post.update_attributes(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.json { render json: @post, status: :created, location: @post }
      else
        format.html { render action: "new" }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end


  # PUT /posts/1
  # PUT /posts/1.json
  def update
    require 'CanvasToImage'
    @post = Post.find(params[:id])
    post_params[:image] = parse_image(post_params[:image])

    respond_to do |format|
      if @post.update_attributes(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end

    # clean up file
    # file.close
    # file.unlink
  end

  def manage_selected_categories
    @categories = Category.all
    respond_to do |format|
      format.html
      format.js
      format.json
    end
  end

  def categorize_selected
    posts = Post.find post_params
    categories = Category.find params[:categories]
    posts.each do |post|
      post.categories = categories
      unless post.save
        # catch error here
      end
    end

    respond_to do |format|
      format.html
      format.js
      format.json
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post = Post.find(params[:id])
    @post.destroy

    respond_to do |format|
      format.html { redirect_to posts_url }
      format.json { head :no_content }
    end
  end


  private

  def parse_image(image_data)
    require 'CanvasToImage'

    File.open("tmp/reply.png", "wb") { |f| f.write(CanvasToImage::decode_data_uri(image_data)[0]) }

    File.open("tmp/reply.png", "r")
  end

  def post_params
    params.require(:post).permit!
  end

end

app/helpers/posts_helper.rb
module PostsHelper
	def recent_blogs
		Post.by_category("blog")
	end

	def recent_experiments
		Post.by_category("experiment")
	end
end

app/views/posts/_category_list.html.erb
<div>
	<% categories.each do |cat| %>
		<%= check_box_tag "categories[]", cat.id %> <%= label_tag "#{cat.name}" %>
	<% end -%>
</div>

app/views/posts/_form.html.erb
<div class="row">
  <div class="column">
    <ul id="post_menu">
      <li class="attachments_menu_button button">
        <a href="<%= attachments_path(post_id: @post.id) %>" id="attachment_button">Attachments</a>
        <div id="attachment_menu">
          <div id="attachment_index">
          </div>
          <div id="attachment_show_edit">
          </div>
        </div>
      </li>
    </ul>
  </div>
</div>
<div class="row">
  <div class="columns">
    <%= form_for(@post, :html => { :multipart => true } ) do |f| %>
      <div class="row">
      <% if @post.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(@post.errors.count, "error") %> prohibited this post from being saved:</h2>
          <ul>
          <% @post.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
          <% end %>
          </ul>
        </div>
      <% end %>
      </div>

      <div class="row">
        <div class="small-2 columns"><%= f.label :title %> </div>
        <div class="small-10 columns"><%= f.text_field :title %></div>
      </div>

      <div class="row">
        <div class="small-2 columns"><%= f.label :description %> </div>
        <div class="small-10 columns"><%= f.text_field :description %></div>
      </div>

      <div class="row"><div class="column"><%= f.label :content %> </div></div>
      <div class="row"><div class="column"><%= f.text_area :content, rows:25 %></div></div>

      <div class="row">
        <div class="column"><%= f.hidden_field :image %></div>
      </div>
      <div class="row actions">
          <div class="small-1 small-offset-10 columns"><%= icon_submit_link("icon-save", "Save", "submit") %></div>
          <div class="small-1 columns"><%= link_to 'Back', posts_path %></div>
      </div>

    <% end %>
  </div>
</div>

app/views/posts/_preview_post.html.erb
<% if logged_in? %>
  <div class="selector"><%= check_box_tag post.id %></div>
<% end -%>
<div class="post">
	<div class="post_header">
		
		
		<h2 class="post_title"><%= link_to( (content_tag(:span,'',:class=>'post_title_pointer')+post.title), post) %></h2>
		<div class="post_desc">
		  <span><%= post.description %></span>
		</div>
	</div>
		
		<div class="hide_n_show_text post_content">
		<% if post.image.present? %>
		<div class="post_image">
			<%= image_tag post.image.url(:thumb) %>
		</div>
		<% end -%>
		  <span id="short_<%=post.id%>" class="short_text"><%= post.content.present? ? post.content[0..140] : "" %>...</span>
		  <span id="long_<%=post.id%>" class="long_text" ><%= post.content %></span>
		</div>
		<div class="clear"></div>
	<div class="post_footer">
		<% if logged_in? %>
	  <span><%= link_to 'Show', post %></span>
	  <span><%= link_to 'Edit', edit_post_path(post) %></span>
	  <span><%= link_to 'Destroy', post, method: :delete, data: { confirm: 'Are you sure?' } %></span>
		<% end -%>
	</div>
</div>

app/views/posts/_quick_view.html.erb
<article class="post inset-shadow">
  <div class="row post_header">

    <div class="small-3 medium-2 columns">
      <div class="row column date-stamp text-center" data-post-date="<%= post.created_at %>">
        <div class="column">
          <div class="row black band month text-center"><div class="column"><%= post.created_at.strftime("%^b") %></div></div>
          <div class="row band day text-center"><div class="column"><%= post.created_at.strftime("%d") %></div></div>
          <div class="row black band year text-center"><div class="column"><%= post.created_at.strftime("%Y") %></div></div>
        </div>
      </div>
    </div>
    <div class="small-9 medium-6 columns">
      <div class="row"><h3 class="column post_title"><%= link_to( (content_tag(:span,'',:class=>'post_title_pointer')+post.title), post) %></h3></div>
      <div class="row ">
        <div class="column"><%= post.description %></div>
      </div>
    </div>
    <div class="small-9 medium-4 columns">
      <img src="http://placehold.it/400x240&text=[img]"/>
    </div>
  </div>
</article>

app/views/posts/categorize_selected.html.erb
$.facebox.close()

app/views/posts/edit.html.erb
<h1>Editing post</h1>

<%= render 'form' %>

<%= link_to 'Show', @post %>

app/views/posts/index.html.erb
<% content_for :css do %>
   <%= stylesheet_link_tag 'blog', media: 'all' %>
<% end -%>


<div class="row">
  <div class="column"><%= react_component("BlogIndexPage", render(template: 'posts/index.json.jbuilder')) %></div>
</div>

app/views/posts/manage_selected_categories.html.erb
<%= form_for :posts, :url=>categorize_selected_posts_path, :remote=>true, :id=>"post_index" do |f| %>
	<div id="selected_posts">
	</div>
	<%= render(:partial=>"category_list", :locals=>{:f=>f, :categories => @categories}) %>
	<%= submit_tag %>
<% end -%>
<script>
	var selected = getSelected();
	$(selected).each(function(){
		var new_input = $("<input type='hidden' value='" + this + "' name='posts[]'/>");
		new_input.appendTo("#selected_posts");
	})
</script>

app/views/posts/new.html.erb
<% content_for :javascript do %>
  <%= javascript_include_tag 'manage_blog' %>
  <%= javascript_include_tag 'blogs' %>
<% end %>

<% content_for :css do %>
   <%= stylesheet_link_tag 'blog', media: 'all' %>
<% end -%>

<base href="/posts" > </base>

<div ng-app="blogApp">
  <div error-messages > </div>

  <div ui-view autoscroll="top">Loading</div>

</div>

app/views/posts/show.html.erb
<div class="row">
  <div class="large-12 columns">
    <p id="notice"><%= notice %></p>
    <h1>
      <%= @post.title %>
    </h1>

    <p class="description" >
      <%= @post.description %>
    </p>

    <div>
      <iframe id="preview"></iframe>
    </div>

    <div>
      <%= @post.content %>
    </div>

      <script>
        $(function(){
          window.updateiFrame("#preview","<%= j(raw @post.html) %>","<%= j @post.css %>", "<%= j @post.javascript %>");
         });
      </script>

    <% if logged_in? %>
    <%= link_to 'Edit', edit_post_path(@post) %> |
    <% end %>
    <%= link_to 'Back', :back %>
  </div>
</div>